"""update users table

Revision ID: 7d5960b5d58a
Revises: 474a0d38407a
Create Date: 2025-01-09 17:02:37.684539

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7d5960b5d58a"
down_revision: str | None = "474a0d38407a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_foo_bar", "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_users_foo_bar", "users", ["foo", "bar"])
    # ### end Alembic commands ###
